"""ModelingAgent — extracts asm_config_before.json / asm_config_after.json from asm_plan.md.

asm_config_before.json has 8 fields matching asmlibrary.run_pipeline kwargs:
  modelcomplex / calibmode / sens_targets / xlsx_path
  sens_delta / senstopk / maxiter
  boundaries: {aeration, internal_recycle, ras_recycle, hydraulic, carbon_dose, chem_dose}

If reflection_agent rejects the config, control returns to this node for regeneration.
This node can read state['reflection_issues'] as repair guidance.
"""
from __future__ import annotations

import json
import sys

from .. import config
from ..state import AgentState
from ..utils import chat, extract_json_block

sys.path.insert(0, str(config.SCRIPT_DIR))
from config_finalize import write_after_config  # noqa: E402


REQUIRED_KEYS = (
    "modelcomplex", "calibmode", "sens_targets", "xlsx_path",
    "sens_delta", "senstopk", "maxiter", "boundaries",
)
BOUNDARY_KEYS = (
    "aeration", "internal_recycle", "ras_recycle",
    "hydraulic", "carbon_dose", "chem_dose",
)
EXTRA_TOP_LEVEL_KEYS = (
    "sens_path", "calib_path", "boundary_terms", "massbalance",
    "K_sub_L_sep_a", "S_sub_O_sep_sat", "K_L_a", "S_O_sat",
)


SYSTEM_PROMPT = r"""You are ModelingAgent in the langgraph-en system. Your job is to extract a machine-readable asm_config.json from the English prose asm_plan.md generated by plan_agent. The JSON is the kwargs mirror for asmlibrary.run_pipeline.

# Output format (mandatory)

Output exactly one ```json``` code block, with no surrounding explanation and no other code blocks. The JSON must strictly use the following 8-field structure:

```json
{
  "modelcomplex": "IntegratedNPR",
  "calibmode": "<SingleNRMSE | WeightedNRMSE | ParetoMOEA>",
  "sens_targets": {"S_sub_NO_sub_3": 0.3, "S_sub_PO_sub_4": 0.7},
  "xlsx_path": "input/data.xlsx",
  "sens_delta": "<float from 0.05 to 0.20>",
  "senstopk": "<integer from 2 to 10>",
  "maxiter": 150,
  "boundaries": {
    "aeration": null,
    "internal_recycle": null,
    "ras_recycle": null,
    "hydraulic": null,
    "carbon_dose": null,
    "chem_dose": null
  }
}
```

The template above shows allowed choices/ranges for `calibmode`, `sens_delta`, and `senstopk`; your actual JSON output must replace those placeholders with concrete values of the correct type.

# Field rules

## modelcomplex (string, choose one of 4)
Extract from asm_plan.md `## 1. Define Model Boundaries`. plan_agent has already judged nitrogen-pathway complexity and phosphorus signals; preserve that choice and do not upgrade to IntegratedNPR unless the plan explicitly says so:
- `"SimplifiedCODN"` — 13 components / 9 reactions; simplified COD-N with one-step nitrification; for COD/ammonia only and no P.
- `"CompleteNRN2O"` — 17 components / 32 reactions; complete N plus N2O intermediate; for N2O / three-step nitrification and no P.
- `"EBPRCODN"` — 17 components / 18 reactions; simplified COD-N plus biological phosphorus removal; the default P model when N complexity is simple or unspecified.
- `"IntegratedNPR"` — 21 components / 41 reactions; complete N + P + N2O; only when complete N, complete P, and N2O are all explicitly required.

Counterexample: if the plan combines "simple denitrification" with calibration targets `S_sub_PO_sub_4` / `X_sub_PHA`, the correct model is `EBPRCODN`, not `IntegratedNPR`.

## calibmode (string, choose one of 3)
Extract from asm_plan.md `## 8. Run Parameter Calibration`:
- `"SingleNRMSE"` — single-target Nelder-Mead; `sens_targets` must contain exactly 1 key.
- `"WeightedNRMSE"` — weighted multi-target Nelder-Mead; `sens_targets` must contain 2-5 keys with weights.
- `"ParetoMOEA"` — NSGA-II Pareto multi-objective optimization; `sens_targets` must contain 2-5 keys.

## sens_targets (dict<string, float>; keys are component variable names, values are weights)
Keys must use only the following 21 variable names. Do not use English prose names or Chinese names:
`S_sub_S`, `S_sub_I`, `S_sub_NH_sub_4`, `S_sub_NO_sub_2`, `S_sub_NO_sub_3`, `S_sub_NH_sub_2OH`, `S_sub_N_sub_2`, `S_sub_N_sub_2O`, `S_sub_NO`, `S_sub_ALK`, `S_sub_O_sub_2`, `X_sub_S`, `X_sub_I`, `X_sub_H`, `X_sub_AOB`, `X_sub_NOB`, `X_sub_STO`, `S_sub_PO_sub_4`, `X_sub_PP`, `X_sub_PAO`, `X_sub_PHA`。

- calibmode = `SingleNRMSE` -> exactly 1 key, usually with weight 1.
- calibmode = `WeightedNRMSE` -> 2-5 keys; copy plan weights if present, otherwise use equal weights.
- calibmode = `ParetoMOEA` -> 2-5 keys; NSGA-II itself does not use weights, so use equal weights by default.
- Keys must belong to the active component subset for modelcomplex.

## xlsx_path (string)
Extract from asm_plan.md `## 7. Run Sensitivity Analysis with Data`, such as `"input/data1.xlsx"` or `"input/data.xlsx"`. Keep it consistent with the plan.

## sens_delta (float)
Single-parameter +/-Delta perturbation size for OAT sensitivity analysis. Use the plan value; if absent, choose a concrete value from `0.05` to `0.20`.

## senstopk (integer)
Top-K sensitivity-ranked parameters entering calibration. Use the plan value; if absent, choose a concrete integer from `2` to `10`.

## maxiter (integer)
Maximum calibration iterations. Use the plan value; if absent, choose a concrete integer from `50` to `200`.

## boundaries (dict; all 6 fixed keys must appear)

```
{
  "aeration": null | {"K_L_a": <float>, "S_O_sat": <float>},
  "internal_recycle": null | {"k_r": <float>, "<component>": <ref>, ...},
  "ras_recycle": null | {"k_RAS": <float>, "factor": <float>},
  "hydraulic": null | {"k_HRT": <float>, "C_in": null | {<component>: <concentration>, ...}},
  "carbon_dose": null | {"r_dose": <float>},
  "chem_dose": null | {"r_chem": <float>}
}
```

Fill strictly from the boundary-configuration list in asm_plan.md `## 6. Build Mass-Balance Equations`:

- Plan says "Aeration boundary: K_L_a=15, S_O_sat=8.0" -> `"aeration": {"K_L_a": 15, "S_O_sat": 8.0}`
- Plan says "Internal recycle boundary: k_r=0.5, S_sub_NO_sub_3=25, S_sub_O_sub_2=0.5" -> `"internal_recycle": {"k_r": 0.5, "S_sub_NO_sub_3": 25.0, "S_sub_O_sub_2": 0.5}`
- Plan says "RAS recycle boundary: k_RAS=0.5, factor=2.0" -> `"ras_recycle": {"k_RAS": 0.5, "factor": 2.0}`
- Plan says "Hydraulic boundary: k_HRT=0.2" -> `"hydraulic": {"k_HRT": 0.2, "C_in": null}`
- Plan says "External carbon-dose boundary: r_dose=10" -> `"carbon_dose": {"r_dose": 10.0}`
- Plan says "Chemical-dose boundary: r_chem=-2.0" -> `"chem_dose": {"r_chem": -2.0}`

Boundary types absent from the plan must be `null`. In a reaction-only scenario, all 6 values are `null`.

# Forbidden

- Do not output extra fields such as `sens_path`, `calib_path`, `boundary_terms`, `massbalance`, `K_sub_L_sep_a`.
- Do not use values in boundaries unless they appear in the plan.
- Do not use Chinese names or English prose names in sens_targets.
- Do not output multiple JSON blocks or any surrounding prose.

Output exactly one ```json``` code block."""


def _build_user_prompt(asm_plan_md: str, prev_issues: list[str] | None) -> str:
    issues_block = ""
    if prev_issues:
        bullets = "\n".join(f"- {x}" for x in prev_issues)
        issues_block = f"""

# Issues in the previous asm_config.json (reflection_agent feedback; fix each item)
{bullets}
"""
    return f"""# asm_plan.md (generated by plan_agent; includes ## User Input / ## Process Identification Summary / Steps 1-9)

{asm_plan_md}
{issues_block}
Extract the asm_plan.md above into exactly one ```json``` code block according to the system-message rules. Use the 8 required fields and the nested 6-key boundaries object. Do not output extra fields or surrounding prose."""


def modeling_agent(state: AgentState) -> dict:
    """Read asm_plan.md -> extract asm_config.json with the LLM -> write midoutput config files."""
    log = list(state.get("log", []))

    asm_plan_md = state.get("asm_plan_md") or (
        config.PLAN_PATH.read_text(encoding="utf-8") if config.PLAN_PATH.exists() else ""
    )
    if not asm_plan_md.strip():
        log.append("[modeling_agent] [FATAL] asm_plan.md is missing or empty")
        return {"log": log, "fatal_error": "asm_plan.md is missing or empty; cannot extract asm_config.json"}

    prev_issues = state.get("reflection_issues") or []
    print("[modeling_agent] Calling the LLM to extract asm_config.json from asm_plan.md...", flush=True)
    raw = chat(SYSTEM_PROMPT, _build_user_prompt(asm_plan_md, prev_issues))
    print("[modeling_agent] LLM response received; parsing JSON...", flush=True)

    cfg = _parse_config_json(raw or "")
    if not isinstance(cfg, dict):
        log.append("[modeling_agent] [WARN] LLM output could not be parsed as a JSON dict; handing back to reflection for retry")
        return {
            "asm_config_before": None,
            "reflection_issues": ["LLM output could not be parsed as a JSON dict for asm_config.json"],
            "log": log,
        }

    cfg.pop("params", None)

    if not config.CANDIDATE_CONFIG_PATH.exists():
        config.CANDIDATE_CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
        config.CANDIDATE_CONFIG_PATH.write_text(
            json.dumps(cfg, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        log.append(f"[modeling_agent] Recorded first candidate config {config.CANDIDATE_CONFIG_PATH.name}")

    cfg = _sanitize_config_shape(cfg)

    config.ASM_CONFIG_BEFORE_PATH.parent.mkdir(parents=True, exist_ok=True)
    config.ASM_CONFIG_BEFORE_PATH.write_text(
        json.dumps(cfg, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    try:
        write_after_config(
            config.ASM_CONFIG_BEFORE_PATH,
            config.ASM_CONFIG_AFTER_PATH,
            config.PARAM_MEANING_PATH,
        )
    except Exception as e:
        log.append(f"[modeling_agent] [FATAL] Failed to generate asm_config_after.json: {e}")
        return {"log": log, "fatal_error": f"Failed to generate asm_config_after.json: {e}"}

    log.append(
        f"[modeling_agent] Wrote {config.ASM_CONFIG_BEFORE_PATH.name}: "
        f"modelcomplex={cfg.get('modelcomplex')}, "
        f"calibmode={cfg.get('calibmode')}, "
        f"sens_targets={cfg.get('sens_targets')}"
    )
    log.append(f"[modeling_agent] Wrote {config.ASM_CONFIG_AFTER_PATH.name}")
    boundaries = cfg.get("boundaries") or {}
    active_bnd = [k for k, v in boundaries.items() if v is not None]
    log.append(f"[modeling_agent] Active boundary types: {active_bnd if active_bnd else '(none; reaction-only scenario)'}")

    return {"asm_config_before": cfg, "log": log}


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------
def _parse_config_json(raw: str) -> dict | None:
    """Extract the 8-field JSON object from the LLM response. Return None on failure."""
    block = extract_json_block(raw)
    if block:
        try:
            return json.loads(block)
        except Exception:
            pass
    # Fallback: find the first complete JSON object.
    first = raw.find("{")
    if first < 0:
        return None
    depth = 0
    in_string = False
    escape_next = False
    for i in range(first, len(raw)):
        c = raw[i]
        if escape_next:
            escape_next = False
            continue
        if c == "\\" and in_string:
            escape_next = True
            continue
        if c == '"':
            in_string = not in_string
            continue
        if in_string:
            continue
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                try:
                    return json.loads(raw[first:i + 1])
                except Exception:
                    return None
    return None


def _sanitize_config_shape(cfg: dict) -> dict:
    """Keep only the 8 top-level fields supported by run_pipeline and normalize boundaries."""
    cfg.pop("params", None)
    for k in EXTRA_TOP_LEVEL_KEYS:
        cfg.pop(k, None)

    cleaned = {k: cfg[k] for k in REQUIRED_KEYS if k in cfg}
    bnd = cleaned.get("boundaries")
    if not isinstance(bnd, dict):
        cleaned["boundaries"] = {k: None for k in BOUNDARY_KEYS}
        return cleaned

    cleaned["boundaries"] = {
        k: (bnd.get(k) if isinstance(bnd.get(k), dict) else None)
        for k in BOUNDARY_KEYS
    }
    return cleaned
